### ISSUE TITLE
Just a message :)

### ISSUE THREAD

**Issue by leodurandfr** [gregtbrown/whatsPlaying#1]
Hello Greg,

I'm replying to you here instead of [Nowify github page](https://github.com/jonashcroft/Nowify/issues/45#issuecomment-1761527784).

Your project is really cool, and I wanted to talk to you because I worked on a similar project which could be interesting to share.

I build a Spotify Ampl with a Raspberry Pi 4, an audio amp hat (Hifiberry Amp2), a 7-inch touch display and a homemade wooden case.

About the Spotify player, I first did it like yours with some help, using Spotify API only to play and display information on screen. Everything was working really well, but I wanted my girlfriend to be able to connect to the speakers by only having to select the raspberry amp as a speaker device in Spotify.

Everything had to be redone using "librespot-java" to turn my Spotify Amp as a "speaker" device and be accessible by everybody connected to the same network. The fact that I am actually a designer and not a developer at all, and know nothing about java, I needed huge help. So I've found someone to rebuild it this way. My Spotify Audio Amp know uses "zeroconf" authentication, which make it visible as a speaker.

Here is a video of my amp when I was still using Spotify API (works and looks exactly like today).

https://github.com/gregtbrown/whatsPlaying/assets/16543063/84f9f3a2-633a-4310-ad32-8643899de13b

I don't know if you intended to keep working on it, in any case, it would be a pleasure to share to you my react or java app in case you are interested. :)

Have a great day,
Léo

**Comment by gregtbrown** [comment]
Hi Léo,

If you want to play _and_ display on the same device, it's really about 
separation of concerns.

1) you can use raspotify (https://dtcooper.github.io/raspotify/) to turn 
a PI into a spotify device that can stream and play spotify music.  Java 
is complete overkill for this.  I also have a PI that uses a hifiberry 
amp.

2) displaying what's playing (the UI) is a completely separate process 
that involves polling the spotify api... nothing to do with actually 
playing music on the device.

You can have either one or both on the same device,  Meaning, you can 
put my app on the same PI that's used for playing music... or not.

Also, as I stated in my readme, I explicitly did not want to use any 
giant frameworks (like react) for the app UI, since imo it is also 
complete overkill for something so simple.  It is also a giant barrier 
to entry for anyone wanting to fork my app that does not know react.


Btw, I do like the design of your player, it turned out nice.

Greg


------ Original Message ------
From "Leshauts" ***@***.***>
To "gregtbrown/whatsPlaying" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 10/15/2023 9:31:25 AM
Subject [gregtbrown/whatsPlaying] Just a message :) (Issue #1)

**Comment by leodurandfr** [comment]
Hi again,

Maybe my message was confused. I just wanted to share my project and what I tried to do without any code experience. The all process to connect to Spotify and play is not my code, i only did the design and html/css. I did not intend to criticize any of what you did.

Somebody advised my to use “librespot-java”, so I looked to do it this way. And I wouldn’t have used react if i knew I couldn’t... 

Thanks for your feedback, I’ll take a look of what you advised.

Leo

**Comment by gregtbrown** [comment]
Hi,No offense taken at all, I was just trying to explain my strategy.Thanks for sharing your project On Oct 15, 2023, at 3:10 PM, Leshauts ***@***.***> wrote:﻿
Hi again,
Maybe my message was confused. I just wanted to share my project and what I tried to do without any code experience. The all process to connect to Spotify and play is not my code, i only did the design and html/css. I did not intend to criticize any of what you did.
Somebody advised my to use “librespot-java”, so I looked to do it this way. And I wouldn’t have used react if i knew I couldn’t...
Thanks for your feedback, I’ll take a look of what you advised.
Leo
